spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/SpringPrac_SimpleWebApplication
    username: hwibin
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      #      show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
#    org.springframework.web: DEBUG
#   org.hibernate.type: trace

