spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/SpringPrac_SimpleWebApplication
    username: hwibin
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
#      show_sql: true
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: DEBUG

